# Generated by Django 3.2.8 on 2022-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favoriteStory',
            field=models.IntegerField(),
        ),
    ]
