# Generated by Django 3.2.8 on 2022-01-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_storyauthor'),
        ('favorites', '0002_alter_favorite_favoritestory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favoriteStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
        ),
    ]
