# Generated by Django 3.2.8 on 2022-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_storydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyGenre',
            field=models.CharField(max_length=100),
        ),
    ]
