# Generated by Django 3.2.8 on 2022-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_storydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyAuthor',
            field=models.CharField(max_length=500),
        ),
    ]
