# Generated by Django 3.2.8 on 2022-01-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_storyauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyDocument',
            field=models.TextField(),
        ),
    ]
